import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  // {
  //   path: "",
  //   title: "Personal",
  //   icon: "",
  //   class: "nav-small-cap",
  //   label: "",
  //   labelClass: "",
  //   extralink: true,
  //   submenu: [],
  // },
  {
    path: "/dashboard",
    title: "Dashboard",
    icon: "mdi mdi-gauge",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  // {
  //   path: "",
  //   title: "UI Components",
  //   icon: "",
  //   class: "nav-small-cap",
  //   label: "",
  //   labelClass: "",
  //   extralink: true,
  //   submenu: [],
  // },
  {
    path: "component/accordion",
    title: "Product Inventory",
    icon: "mdi mdi-equal",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/alert",
    title: "Push New Products",
    icon: "mdi mdi-message-bulleted",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/carousel",
    title: "Reports",
    icon: "mdi mdi-view-carousel",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/dropdown",
    title: "Payments",
    icon: "mdi mdi-arrange-bring-to-front",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/modal",
    title: "Delivery",
    icon: "mdi mdi-tablet",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/pagination",
    title: "Reviews",
    icon: "mdi mdi-backburger",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/poptool",
    title: "Issues & Trackings",
    icon: "mdi mdi-image-filter-vintage",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/progressbar",
    title: "BH Bundle Modify",
    icon: "mdi mdi-poll",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  // {
  //   path: "/component/rating",
  //   title: "Ratings",
  //   icon: "mdi mdi-bandcamp",
  //   class: "",
  //   label: "",
  //   labelClass: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/tabs",
  //   title: "Tabs",
  //   icon: "mdi mdi-sort-variant",
  //   class: "",
  //   label: "",
  //   labelClass: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/timepicker",
  //   title: "Timepicker",
  //   icon: "mdi mdi-calendar-clock",
  //   class: "",
  //   label: "",
  //   labelClass: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/buttons",
  //   title: "Button",
  //   icon: "mdi mdi-toggle-switch",
  //   class: "",
  //   label: "",
  //   labelClass: "",
  //   extralink: false,
  //   submenu: [],
  // },
  {
    path: "/component/tabs",
      title: "Manage Discounts",
      icon: "mdi mdi-calendar-clock",
      class: "",
      label: "",
      labelClass: "",
      extralink: false,
      submenu: [],
    },
  {
     path: "/component/buttons",
       title: "Manage Promotion ",
       icon: "mdi mdi-toggle-switch",
       class: "",
       label: "",
       labelClass: "",
       extralink: false,
       submenu: [],
     },
  {
    path: "/component/cards",
    title: "Customer Support",
    icon: "mdi mdi-blur-radial",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  },
  
  {
       path: "",
       title: "Admin Console",
       icon: "",
       class: "nav-small-cap",
       label: "",
       labelClass: "",
       extralink: true,
       submenu: [],
     },
  {
    path: "/component/buttons",
    title: "Administration",
    icon: "mdi mdi-bandcamp",
    class: "",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [],
  }
  // {
  //   path: "/component/toast",
  //   title: "Toast",
  //   icon: "mdi mdi-message-reply-text",
  //   class: "",
  //   label: "",
  //   labelClass: "",
  //   extralink: false,
  //   submenu: [],
  // },
];
